server:
  port: 7001
  servlet:
    context-path: /express-user
spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 1024MB
  application:
    name: eureka-client-express-user
  thymeleaf:
    cache: false
    check-template: true
    check-template-location: true
    enabled: true
    encoding: UTF-8
    excluded-view-names:
    mode: HTML5
    prefix: classpath:/templates/
    suffix: .html
    servlet:
      content-type: text/html
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/express?serverTimezone=UTC
      driverClassName: com.mysql.cj.jdbc.Driver
      max-active: 20
      min-idle: 8
      initial-size: 10
    username: root
    password: 123456
  redis:
    database: 3
    host: 127.0.0.1
    port: 6379
    timeout: 10000
  messages:
    basename: i18n.login
mybatis-plus:
  global-config:
    db-config:
      table-prefix: t_
      id-type: auto
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.express.user.domain
  configuration:
    map-underscore-to-camel-case: true

eureka:
  client:
    service-url:
      defaultZone: http://server1:8000/eureka/



file:
  uploadPath: static\pages\photo\